version: '3.8'

services:
  workspace:
    container_name: apex_captain_mono_repo_template_devcon_workspace
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        NODE_VERSION: 16

    volumes:
      - ..:/workspace:cached
      - ApexCaptain-MonoRepoTemplate-WorkSpace-node_mnodules:/workspace/node_modules

    env_file:
      - env/devcontainer.github-secrets.env

    command: sleep infinity
    user: node

volumes:
  ApexCaptain-MonoRepoTemplate-WorkSpace-node_mnodules:
